### ISSUE TITLE
Issues instrumenting NewRelic from hook

### ISSUE THREAD

**Issue by jasonsims** [Kikobeats/sails-hook-newrelic#3] opened 2015-03-12 18:49 UTC
How do you get around the requirement of having `require('newrelic')` as the first executed line of the application? I normally add this line to the `app.js` file in the project root and run my apps with `node app.js`. However, if it's missing from there the New Relic UI complains with:

> Some modules were uninstrumented during the current time window: connect, express, mongodb. Make sure require('newrelic'); is the first line of the application's main module.

**Comment by Kikobeats** [comment] 2015-03-13 08:30
Yes, is a little problem, but this hook is for try delete the friction :-)

I added a `register.js`, so, in your `app.js` you put `require('sails-hook-newrelic/register');` in the first line and the config is loaded. The problem is how to avoid this under different `production` environment

Another problem related with this way to load is how to sails access to newrelic object... I using a global object and assign this but is a little ugly. maybe @mikermcneil can help about this.

**Comment by Kikobeats** [comment] 2015-03-13 09:11
@jasonsims check now, I added a `register.js`, so, in your `app.js` you put `require('sails-hook-newrelic/register');` in the first line and the config is loaded :-)

the problem is how to avoid this under different `production` environment

**Comment by Kikobeats** [comment] 2015-03-13 09:15
maybe @mikermcneil can help about how to pass newrelic object from out of sails

**Closed as completed** 2015-03-24 15:44 UTC
